"""Add description field to categories

Revision ID: 323e252492b0
Revises: cfed27705f5d
Create Date: 2025-08-04 11:03:51.189582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323e252492b0'
down_revision = 'cfed27705f5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###