"""Add order verification fields and admin settings table

Revision ID: 3445af785623
Revises: 077f07d7a72d
Create Date: 2025-08-08 15:16:06.373201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3445af785623'
down_revision = '077f07d7a72d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('setting_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_settings_key'), 'admin_settings', ['key'], unique=True)
    op.add_column('order_items', sa.Column('actual_weight', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('actual_quantity', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('actual_price_per_unit', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('actual_total_price', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('weight_variance_percent', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('price_variance_percent', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('expected_total', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('actual_total', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('price_variance_percent', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('auto_confirmed', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('verified_by', sa.String(), nullable=True))
    op.alter_column('products', 'packages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'packages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('orders', 'verified_by')
    op.drop_column('orders', 'verified_at')
    op.drop_column('orders', 'auto_confirmed')
    op.drop_column('orders', 'price_variance_percent')
    op.drop_column('orders', 'actual_total')
    op.drop_column('orders', 'expected_total')
    op.drop_column('order_items', 'price_variance_percent')
    op.drop_column('order_items', 'weight_variance_percent')
    op.drop_column('order_items', 'actual_total_price')
    op.drop_column('order_items', 'actual_price_per_unit')
    op.drop_column('order_items', 'actual_quantity')
    op.drop_column('order_items', 'actual_weight')
    op.drop_index(op.f('ix_admin_settings_key'), table_name='admin_settings')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###