"""Add bot interaction tracking to users

Revision ID: 7d62d9d33d94
Revises: e2a8ab370123
Create Date: 2025-08-04 20:14:12.347338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d62d9d33d94'
down_revision = 'e2a8ab370123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_interactions_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_bot_interaction', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('first_bot_interaction', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_bot_interaction')
    op.drop_column('users', 'last_bot_interaction')
    op.drop_column('users', 'bot_interactions_count')
    # ### end Alembic commands ###