"""Add product_packages table with image support

Revision ID: bd93ea366fcd
Revises: 7528a4e0b893
Create Date: 2025-08-05 12:25:03.653755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd93ea366fcd'
down_revision = '7528a4e0b893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'package_id', name='uq_product_package_id')
    )
    op.create_index(op.f('ix_product_packages_id'), 'product_packages', ['id'], unique=False)
    op.create_index(op.f('ix_product_packages_package_id'), 'product_packages', ['package_id'], unique=False)
    op.create_index(op.f('ix_product_packages_product_id'), 'product_packages', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_packages_product_id'), table_name='product_packages')
    op.drop_index(op.f('ix_product_packages_package_id'), table_name='product_packages')
    op.drop_index(op.f('ix_product_packages_id'), table_name='product_packages')
    op.drop_table('product_packages')
    # ### end Alembic commands ###