"""Add order_id field to orders table

Revision ID: e2a8ab370123
Revises: 323e252492b0
Create Date: 2025-08-04 16:03:36.889175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a8ab370123'
down_revision = '323e252492b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('orders', sa.Column('order_id', sa.Integer(), nullable=True))
    
    # Set order_id for existing orders starting from 100
    connection = op.get_bind()
    connection.execute(sa.text("""
        WITH numbered_orders AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY id) as rn
            FROM orders
        )
        UPDATE orders 
        SET order_id = 99 + numbered_orders.rn
        FROM numbered_orders
        WHERE orders.id = numbered_orders.id
    """))
    
    # Make the column not nullable and add unique constraint
    op.alter_column('orders', 'order_id', nullable=False)
    op.create_unique_constraint(None, 'orders', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###