"""Add admin_users table

Revision ID: f91318820a54
Revises: 7d62d9d33d94
Create Date: 2025-08-05 10:02:17.246248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91318820a54'
down_revision = '7d62d9d33d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###